const createNewPropertyPersonInChargeCompany = require("./create_new_property_person_in_charge_company");
const getAllPropertyPersonInChargeCompanies = require("./get_all_property_person_in_charge_companies");
const getAllPropertyPersonInChargeCompanyWithCondition = require("./get_all_property_person_in_charge_company_with_condition");
const getPropertyPersonInChargeCompanyById = require("./get_property_person_in_charge_company_by_id");
const updatePropertyPersonInChargeCompanyById = require("./update_property_person_in_charge_company_by_id");
const deletePropertyPersonInChargeCompanyById = require("./delete_property_person_in_charge_company_by_id");
const restorePropertyPersonInChargeCompanyById = require("./restore_property_person_in_charge_company_by_id");

module.exports = { createNewPropertyPersonInChargeCompany, getAllPropertyPersonInChargeCompanies, getAllPropertyPersonInChargeCompanyWithCondition, getPropertyPersonInChargeCompanyById, updatePropertyPersonInChargeCompanyById, deletePropertyPersonInChargeCompanyById, restorePropertyPersonInChargeCompanyById };
